# Generated by Django 5.1.3 on 2025-05-07 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dummymodel',
            options={'permissions': [('administrador_roles', 'Administrador de roles'), ('aprobar_anexo_a', 'Puede aprobar anexo A'), ('aprobar_anexo_a1', 'Puede aprobar anexo A1'), ('aprobar_anexo_a2', 'Puede aprobar anexo A2'), ('aprobar_anexo_a3', 'Puede aprobar anexo A3'), ('llenar_anexo_a', 'Puede llenar anexo A'), ('llenar_anexo_a1', 'Puede llenar anexo A1'), ('llenar_anexo_a2', 'Puede llenar anexo A2'), ('llenar_anexo_a3', 'Puede llenar anexo A3'), ('crear_anexo_a', 'Puede crear anexo A'), ('crear_anexo_a1', 'Puede crear anexo A1'), ('crear_anexo_a2', 'Puede crear anexo A2'), ('crear_anexo_a3', 'Puede crear anexo A3')]},
        ),
    ]
