# Generated by Django 5.1.3 on 2024-12-19 23:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bajas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_inv', models.CharField(blank=True, max_length=50)),
                ('inm_herramienta', models.CharField(blank=True, max_length=50)),
                ('denominacion_SAP', models.CharField(max_length=100)),
                ('unidad_org', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='uploaded/')),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(max_length=100)),
                ('motivo_baja', models.CharField(max_length=100)),
                ('destino_final', models.TextField()),
                ('años_explotacion', models.IntegerField()),
                ('valor_residual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('detalle', models.TextField(default='DETERIORADO ÚTIL')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('fecha_solicitud', models.DateField(default=django.utils.timezone.now)),
                ('archivo_anexo_a', models.FileField(blank=True, null=True, upload_to='anexos/')),
                ('archivo_anexo_a1', models.FileField(blank=True, null=True, upload_to='anexos/')),
                ('anexo_a2', models.TextField(blank=True)),
                ('anexo_a3', models.TextField(blank=True)),
                ('archivo_mov_aft', models.FileField(blank=True, null=True, upload_to='anexos/')),
            ],
        ),
    ]
