# Generated by Django 5.1.3 on 2024-11-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bajas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_inv', models.CharField(max_length=50)),
                ('inm_herramienta', models.CharField(max_length=50)),
                ('denominacion_SAP', models.CharField(max_length=100)),
                ('unidad_org', models.TextField()),
                ('anexo_a1', models.CharField(max_length=100)),
                ('anexo_a', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='uploaded/')),
                ('mov_aft', models.CharField(max_length=100)),
                ('anexo_a2', models.CharField(max_length=100)),
                ('anexo_a3', models.CharField(max_length=100)),
                ('observaciones', models.TextField()),
                ('estado', models.CharField(max_length=100)),
                ('motivo_baja', models.CharField(max_length=100)),
                ('destino_final', models.TextField()),
                ('años_explotacion', models.IntegerField()),
                ('valor_residual', models.IntegerField()),
                ('detalle', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
