# Generated by Django 5.1.3 on 2024-11-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bajas',
            name='inm_herramienta',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bajas',
            name='no_inv',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
