# Generated by Django 5.1.3 on 2025-02-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajas', '0002_bajas_archivo_anexo_0_alter_bajas_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='bajas',
            name='area_pertenece',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bajas',
            name='equipo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bajas',
            name='estado_actual',
            field=models.CharField(choices=[('Malo', 'Malo'), ('Regular', 'Regular'), ('Bueno', 'Bueno')], default='Malo', max_length=100),
        ),
        migrations.AddField(
            model_name='bajas',
            name='fabricante',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bajas',
            name='modelo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bajas',
            name='uso_actual',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bajas',
            name='estado',
            field=models.CharField(choices=[('No Procede', 'No Procede'), ('Presentar a CBT', 'Presentar a CBT'), ('Presentar a CBN', 'Presentar a CBN'), ('Espera respuesta CBN', 'Espera respuesta CBN'), ('Aprobado por CBT', 'Aprobado por CBT'), ('Aprobado por CBN', 'Aprobado por CBN'), ('No aprobado (reubicar)', 'No aprobado (reubicar)'), ('No aprobado', 'No aprobado'), ('Espera firma anexo0', 'Espera firma anexo0'), ('Firmado Anexo0', 'Firmado Anexo0'), ('Asignar Responsable', 'Asignar Responsable')], default='No Procede', max_length=100),
        ),
    ]
