# Generated by Django 5.1.3 on 2024-12-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajas', '0004_bajas_archivo_anexo_1_bajas_archivo_anexo_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bajas',
            name='anexo_a',
            field=models.CharField(default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='bajas',
            name='anexo_a1',
            field=models.CharField(default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='bajas',
            name='anexo_a2',
            field=models.CharField(default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='bajas',
            name='anexo_a3',
            field=models.CharField(default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='bajas',
            name='detalle',
            field=models.TextField(default='DETERIORADO ÚTIL'),
        ),
        migrations.AlterField(
            model_name='bajas',
            name='mov_aft',
            field=models.CharField(default='no', max_length=100),
        ),
    ]
