# Generated by Django 5.1.3 on 2025-03-03 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajas', '0004_bajas_archivo_anexo_a2_bajas_archivo_anexo_a3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bajas',
            name='descripcion_est_actual',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
