# Generated by Django 5.1.3 on 2024-12-05 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bajas', '0005_alter_bajas_anexo_a_alter_bajas_anexo_a1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bajas',
            name='anexo_a',
        ),
        migrations.RemoveField(
            model_name='bajas',
            name='anexo_a1',
        ),
        migrations.RemoveField(
            model_name='bajas',
            name='anexo_a2',
        ),
        migrations.RemoveField(
            model_name='bajas',
            name='anexo_a3',
        ),
        migrations.RemoveField(
            model_name='bajas',
            name='mov_aft',
        ),
    ]
