# Generated by Django 5.1.3 on 2025-03-26 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bajas', '0005_bajas_descripcion_est_actual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bajas',
            name='equipo',
        ),
    ]
