# Generated by Django 5.1.3 on 2024-12-05 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bajas', '0006_remove_bajas_anexo_a_remove_bajas_anexo_a1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bajas',
            old_name='archivo_anexo_1',
            new_name='archivo_anexo_a1',
        ),
        migrations.RenameField(
            model_name='bajas',
            old_name='archivo_anexo_2',
            new_name='archivo_anexo_a2',
        ),
        migrations.RenameField(
            model_name='bajas',
            old_name='archivo_anexo_3',
            new_name='archivo_anexo_a3',
        ),
    ]
