# Generated by Django 5.1.3 on 2025-04-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajas', '0006_remove_bajas_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bajas',
            name='anexo_0aprobado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bajas',
            name='anexo_A1aprobado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bajas',
            name='anexo_A2aprobado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bajas',
            name='anexo_A3aprobado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bajas',
            name='anexo_Aaprobado',
            field=models.BooleanField(default=False),
        ),
    ]
