# Generated by Django 5.1.3 on 2025-04-15 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bajas', '0007_bajas_anexo_0aprobado_bajas_anexo_a1aprobado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bajas',
            old_name='anexo_A1aprobado',
            new_name='listopara_anexo_A',
        ),
        migrations.RenameField(
            model_name='bajas',
            old_name='anexo_A2aprobado',
            new_name='listopara_anexo_A1',
        ),
        migrations.RenameField(
            model_name='bajas',
            old_name='anexo_A3aprobado',
            new_name='listopara_anexo_A2',
        ),
        migrations.RenameField(
            model_name='bajas',
            old_name='anexo_Aaprobado',
            new_name='listopara_anexo_A3',
        ),
    ]
