# Generated by Django 5.1.3 on 2024-12-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajas', '0007_rename_archivo_anexo_1_bajas_archivo_anexo_a1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bajas',
            name='archivo_anexo_a2',
        ),
        migrations.RemoveField(
            model_name='bajas',
            name='archivo_anexo_a3',
        ),
        migrations.AddField(
            model_name='bajas',
            name='anexo_a2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bajas',
            name='anexo_a3',
            field=models.TextField(blank=True),
        ),
    ]
