# Generated by Django 5.1.3 on 2025-04-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajas', '0008_rename_anexo_a1aprobado_bajas_listopara_anexo_a_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bajas',
            name='anexo_a2',
        ),
        migrations.RemoveField(
            model_name='bajas',
            name='anexo_a3',
        ),
        migrations.AlterField(
            model_name='bajas',
            name='anexo_0aprobado',
            field=models.BooleanField(default=True),
        ),
    ]
