# Generated by Django 5.1.3 on 2025-04-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajas', '0009_remove_bajas_anexo_a2_remove_bajas_anexo_a3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bajas',
            name='informacion_anexo_a1_completa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bajas',
            name='informacion_anexo_a2_completa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bajas',
            name='informacion_anexo_a3_completa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bajas',
            name='informacion_anexo_a_completa',
            field=models.BooleanField(default=False),
        ),
    ]
