# Generated by Django 5.1.3 on 2025-04-29 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajas', '0010_bajas_informacion_anexo_a1_completa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bajas',
            name='aprobado_anexoA1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bajas',
            name='aprobado_anexoA2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bajas',
            name='aprobado_anexoA3',
            field=models.BooleanField(default=False),
        ),
    ]
