# Generated by Django 5.1.3 on 2025-05-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajas', '0011_bajas_aprobado_anexoa1_bajas_aprobado_anexoa2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bajas',
            name='aprobado_anexoA',
            field=models.BooleanField(default=False),
        ),
    ]
