# Generated by Django 5.1.3 on 2025-06-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajas', '0014_bajas_rechazada_alter_bajas_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bajas',
            name='area_pertenece',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='bajas',
            name='destino_final',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='bajas',
            name='detalle',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='bajas',
            name='estado',
            field=models.CharField(default='No Procede', max_length=100),
        ),
        migrations.AlterField(
            model_name='bajas',
            name='estado_actual',
            field=models.CharField(default='', max_length=100),
        ),
    ]
