# Generated by Django 5.1.3 on 2025-06-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajas', '0015_alter_bajas_area_pertenece_alter_bajas_destino_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bajas',
            name='motivo_baja',
            field=models.CharField(default='', max_length=100),
        ),
    ]
