# Generated by Django 5.1.3 on 2025-06-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajas', '0016_alter_bajas_motivo_baja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bajas',
            name='unidad_org',
            field=models.TextField(default=''),
        ),
    ]
