# Generated by Django 5.1.3 on 2025-06-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajas', '0018_alter_bajas_destino_final_alter_bajas_unidad_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bajas',
            name='unidad_org',
            field=models.CharField(default='', max_length=100),
        ),
    ]
