# Generated by Django 5.1.3 on 2025-06-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajas', '0019_alter_bajas_unidad_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bajas',
            name='destino_final',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bajas',
            name='estado_actual',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bajas',
            name='motivo_baja',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bajas',
            name='unidad_org',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
