# Generated by Django 5.1.3 on 2025-06-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajas', '0020_alter_bajas_destino_final_alter_bajas_estado_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bajas',
            name='detalle',
            field=models.TextField(blank=True, default=''),
        ),
    ]
