# Generated by Django 5.1.3 on 2025-07-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajas', '0021_alter_bajas_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='bajas',
            name='terminada',
            field=models.BooleanField(default=False),
        ),
    ]
