# Generated by Django 5.1.3 on 2025-07-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bajas', '0022_bajas_terminada'),
    ]

    operations = [
        migrations.AddField(
            model_name='bajas',
            name='no_solicitud',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
