# Generated by Django 5.1.3 on 2025-08-24 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bajas', '0023_bajas_no_solicitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bajas',
            name='archivo_mov_aft',
        ),
    ]
